In [2]:
import pandas as pd
import numpy as np

## Python Basics

### Ranges and Arrays
- For creating a series of numbers
- `np.arange(start_num, end_num, steps)`

In [3]:
lst = [1,2,3,4,5]

np.arange(4)

array([0, 1, 2, 3])

In [ ]:
"""
Try returning:
array([5, 10, 15, 20])
"""

np.arange(...)

In [ ]:
# Descending array


In [ ]:
"""
Try returning:
array([10, 7, 4])
"""

np.arange(...)

### Conditions
- Operates by boolean
- `if condition == True`:
    - `print('yes')`
- `else`:
    - `print('no')`
 

In [ ]:
"""
Try returning:
if age is between 15 - 17, print middle school student
if age is between 18 - 20, print high school student
if age is over 20, print adult
else, print else
"""

age = 18
if 15 <= ... <= 17:
    print(...)
elif ...:
    ...

### For Loops
- For iterating over a series of values and repeating certain calculation
- `for i in range(start_num, end_num, steps)`:
    - `Execute a function`
- by default, `for i in range(0, end_num, 1)`

In [ ]:
# Nested for loop
shirt = ['blue', 'purple', 'red']
pants = ['green', 'black', 'white']

In [ ]:
"""
Try returning:
1 ~ 9단 구구단
1 X 1
1 X 2
1 X 3
1 X 4
...
"""
for i in range(1, 9):
    ...

Adding elements to an empty list
- `lst.append(element)`

In [ ]:
numbers = [0, 61, 7, 8, 109]
newnumbers = []
...
print(newnumbers)

Strings
- `stringvalue += 'string'`

In [ ]:
"""
Try creating a new array by appending string values
Return:
['blue shirt', 'purple shirt', 'red shirt']
"""

shirts = ['blue', 'purple', 'red']
clothes = []

for i in ...:
    ...
    
print(clothes)

`break`: stop iterating and exit out of for loop \
`continue`: loop back to the beginning of the loop

In [ ]:
lst = ['hi', 'hello', 'bye']
for i in lst:
    ...

In [ ]:
"""
Try this:
Return pass message if a student's mark is over 60 points
"""
marks = [90, 25, 67, 45, 80]

# student number
number = 0 
for mark in marks: 
    number = ...
    if mark < 60:
        ... 
    print("{}번 학생 축하합니다. 합격입니다. ".format(number))

### Dictionaries
- Operates under key-value relationship
- `dict = {'Jinwoo': 19, 'Emily': 15}`

In [ ]:
a = {'name': 'pey', 'phone': '0119993323', 'birth': '1118'}


In [ ]:
# values()

In [ ]:
# items()

In [ ]:
dict = {'Jinwoo': 19, 'Emily': 15}
# Iterating over dictionary


### While Loop
- For repeating a function until it reaches certain condition
- `while condition:` 
    - `execute a function`

In [ ]:
count = 10


In [ ]:
# watch out for infinite loop!


In [ ]:
# break in while loop
status = True
result = 0

...

print(result)

In [ ]:
"""
Try implementing 
If treehit reaches 10, the tree falls
Until it reaches 10, print the number of treehits

"""

treeHit = 0

while treeHit < 10:
    treeHit = ...
    print("나무를 {}d번 찍었습니다.".format(treeHit)
    if ...:
        print("나무 넘어갑니다.")

In [ ]:
"""
Try implementing a coffee vending machine
Coffee is 300 won.

If a person pays 300 won, sell coffee
If a person pays less than 300 won, return the money and don't sell coffee
If a person pays more than 300 won, sell coffee and return change
If coffee is sold out, break while loop and stop selling

"""

coffee = 5
while True:
    money = int(input("돈을 넣어 주세요: "))
    if money == 300:
        print("커피를 줍니다.")
        coffee = ...
    elif ...:
        print("거스름돈 {}d를 주고 커피를 줍니다.".format(...))
        coffee = ...
    else:
        print("돈을 다시 돌려주고 커피를 주지 않습니다.")
        print("남은 커피의 양은 {}개 입니다.".format(coffee))
    if ...:
        print("커피가 다 떨어졌습니다. 판매를 중지 합니다.")
        break